[package]
name = "vex"
version = "0.1.3"
license = "MIT"
repository = "https://github.com/travistrue2008/vex"
authors = ["Travis J True <travis@truesoftent.com>"]
description = "3D math library"

[dependencies]
